<h1 style="color:brown;">  Hands on practice with neural network</h1> 

### Lesson plan

1. How to evaluate a model? <a href="https://colah.github.io/posts/2015-09-Visual-Information/">cross-entropy</a>
2. Types of Neural Nets
3. Keras & Tensorflow - specialized framework (python library) for machine learning
4. Hands on image reconstruction with Keras (approximately PCA)

### Some types of neural networks  

- Classic - what we did on Friday
- Auto-encoder (like PCA finding compressed representation) - now

the hidden layer is an encoding of the generalization
- Recurrent neural network - coming soon
- Convlutional neural networks - coming soon

![](./img/RNN.png)

![](./img/CNN.png)

![](./img/autorec.png)

### 3. Tensorflow and Keras
##### An Example

### Image Classification
[CIFAR-10](http://www.cs.toronto.edu/~kriz/cifar.html) is a common benchmark in machine learning for image recognition. The CIFAR-10 dataset consists of 60000 32x32 colour images in 10 classes, with 6000 images per class. There are 50000 training images and 10000 test images. 

<img align =left src="./img/c10imgcat.png">

<img align =left src="./img/tf-logo3.png"><br>


This task can be accomplished in TensorFlow and the code can be found [here](https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10/). Let's look at it together. 

<img align =left src="./img/keras.png"><br>

Now, the same task in [in Keras](https://keras.io/examples/cifar10_cnn/). After looking at it and comparing it to the tensorflow code, what do you notice? Any formatting look familiar?

### Similar to another scenario we've seen:

![statsmodels](./img/statsmodels_hybi_banner.png)

vs

![sklearn](./img/sklearn.png )

### Okay, but should I use Keras or Tensorflow?
![wrong question](https://www.pyimagesearch.com/wp-content/uploads/2018/10/keras_vs_tensorflow_wrong_question.jpg)

### Keras is an API

Coded in Python, that can be layered on top of many different back-end processing systems.

![kerasback](./img/keras_2.png)

While each of these systems has their own coding methods, Keras abstracts from that in streamlined pythonic manner we are used to seeing in other python modeling libraries.

Keras development is backed primarily by Google, and the Keras API comes packaged in TensorFlow as tf.keras. Additionally, Microsoft maintains the CNTK Keras backend. Amazon AWS is maintaining the Keras fork with MXNet support. Other contributing companies include NVIDIA, Uber, and Apple (with CoreML).

## Wait, what's TensorFlow?


## Let's start with tensors

## Tensors are multidimensional matricies

![tensor](./img/tensors.png)

### TensorFlow manages the flow of matrix math

That makes neural network processing possible.

![cat](./img/cat-tensors.gif)

## TensorFlow at its start

An open-source library

![more-arch](./img/layers.png)

### 2007 Keras was fully integrated into TensorFlow

It "comes with" Tensorflow and provides all the medium to high end API services to integrate with tensorflow processing.

![tensorflow-prog](./img/tensorflow_programming_environment.png)

### Keras, an API with an intentional UX

- Deliberately design end-to-end user workflows
- Reduce cognitive load for your users
- Provide helpful feedback to your users

[full article here](https://blog.keras.io/user-experience-design-for-apis.html)<br>
[full list of why to use Keras](https://keras.io/why-use-keras/)

### A few comparisons

While you **can leverage both**, here are a few comparisons.

| Comparison | Keras | Tensorflow|
|------------|-------|-----------|
| **Level of API** | high-level API | High and low-level APIs |
| **Speed** |  can *seem* slower |  is a bit faster |
| **Language architecture** | simple architecture, more readable and concise | straight tensorflow is a bit mroe complex |
| **Debugging** | less frequent need to debug | difficult to debug |
| **Datasets** | usually used for small datasets | high performance models and large datasets that require fast execution|

This is also a _**non-issue**_ - as you can leverage tensorflow commands within keras and vice versa. If Keras ever seems slower, it's because the developer's time is more expensive than the GPUs. Keras is designed with the developer in mind. 


[reference link](https://www.edureka.co/blog/keras-vs-tensorflow-vs-pytorch/)

## More levers and buttons

Coding directly in **Tensorflow** allows you to tweak more parameters to optimize performance. The **Keras** wrapper makes the code more accessible for developers prototyping models.

![levers](./img/levers.jpeg)

### Building our first Neural Network - Auto-encoder

#### Install Keras & tensorflow

In [2]:
!pip install tensorflow
!pip install keras

### Keras basic syntax 

<a href="https://keras.io">Documentation</a>

In [9]:
import numpy as np

In [10]:
x_train = np.random.random((1000,20))
x_train

array([[0.83000919, 0.32521522, 0.42921256, ..., 0.02792621, 0.64992864,
        0.74843745],
       [0.35055943, 0.2709626 , 0.69621536, ..., 0.9137257 , 0.85644882,
        0.39296035],
       [0.16271422, 0.87745075, 0.75741009, ..., 0.9761104 , 0.74947231,
        0.81007745],
       ...,
       [0.12878114, 0.16524134, 0.95562218, ..., 0.71801066, 0.95533221,
        0.0540437 ],
       [0.20838243, 0.73268622, 0.91632005, ..., 0.43062195, 0.17900719,
        0.98324706],
       [0.31102581, 0.21676889, 0.44234023, ..., 0.08378513, 0.82087922,
        0.71474132]])

In [11]:
x_train.shape

(1000, 20)

In [12]:
x_test = np.random.random((1000, 20))


In [18]:
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
y_test = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)

In [22]:
y_train.shape

(1000, 10)

In [26]:
Ytrain[1]

array([4])

In [28]:
x_train[1,:]

array([0.35055943, 0.2709626 , 0.69621536, 0.82217201, 0.12458948,
       0.23012142, 0.66277549, 0.67574637, 0.91202092, 0.89108533,
       0.21632025, 0.61228889, 0.6107084 , 0.86881153, 0.97154969,
       0.28153435, 0.24869385, 0.9137257 , 0.85644882, 0.39296035])

In [23]:
y_train[1, :]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [21]:
Ytrain = np.random.randint(10, size=(1000, 1))

In [1]:
import keras

Using TensorFlow backend.


In [5]:
from keras.models import Sequential

In [6]:
model = Sequential()

In [7]:
type(model)

keras.engine.sequential.Sequential

In [8]:
from keras.layers import Dense

In [13]:
model.add(Dense(units = 64, activation = 'relu', input_dim = 20))

In [31]:
model.add(Dense(units = 10, activation = 'softmax', name = 'murat'))

In [32]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                1344      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
_________________________________________________________________
murat (Dense)                (None, 10)                110       
Total params: 2,104
Trainable params: 2,104
Non-trainable params: 0
_________________________________________________________________


In [15]:
model

21.0

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                1344      
Total params: 1,344
Trainable params: 1,344
Non-trainable params: 0
_________________________________________________________________


In [36]:
150*150*1000000

22500000000

In [37]:
model.compile(optimizer= 'sgd', loss = 'categorical_crossentropy', metrics= ['accuracy'])

In [38]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                1344      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
_________________________________________________________________
murat (Dense)                (None, 10)                110       
Total params: 2,104
Trainable params: 2,104
Non-trainable params: 0
_________________________________________________________________


In [41]:
model.fit(x_train, y_train, epochs=100, batch_size=10, validation_split= 0.1)

Train on 900 samples, validate on 100 samples
Epoch 1/100
900/900 [==============================] - 0s 98us/step - loss: 2.2906 - accuracy: 0.1289 - val_loss: 2.3271 - val_accuracy: 0.0700
Epoch 2/100
900/900 [==============================] - 0s 97us/step - loss: 2.2906 - accuracy: 0.1289 - val_loss: 2.3272 - val_accuracy: 0.0700
Epoch 3/100
900/900 [==============================] - 0s 103us/step - loss: 2.2905 - accuracy: 0.1289 - val_loss: 2.3274 - val_accuracy: 0.0700
Epoch 4/100
900/900 [==============================] - 0s 101us/step - loss: 2.2904 - accuracy: 0.1289 - val_loss: 2.3274 - val_accuracy: 0.0700
Epoch 5/100
900/900 [==============================] - 0s 104us/step - loss: 2.2903 - accuracy: 0.1278 - val_loss: 2.3275 - val_accuracy: 0.0700
Epoch 6/100
900/900 [==============================] - 0s 89us/step - loss: 2.2903 - accuracy: 0.1289 - val_loss: 2.3275 - val_accuracy: 0.0700
Epoch 7/100
900/900 [==============================] - 0s 102us/step - loss: 2.2902 - a

Epoch 57/100
900/900 [==============================] - 0s 82us/step - loss: 2.2851 - accuracy: 0.1289 - val_loss: 2.3316 - val_accuracy: 0.0800
Epoch 58/100
900/900 [==============================] - 0s 86us/step - loss: 2.2850 - accuracy: 0.1300 - val_loss: 2.3320 - val_accuracy: 0.0800
Epoch 59/100
900/900 [==============================] - 0s 83us/step - loss: 2.2848 - accuracy: 0.1311 - val_loss: 2.3322 - val_accuracy: 0.0800
Epoch 60/100
900/900 [==============================] - 0s 97us/step - loss: 2.2846 - accuracy: 0.1300 - val_loss: 2.3325 - val_accuracy: 0.0800
Epoch 61/100
900/900 [==============================] - 0s 82us/step - loss: 2.2845 - accuracy: 0.1311 - val_loss: 2.3326 - val_accuracy: 0.0800
Epoch 62/100
900/900 [==============================] - 0s 95us/step - loss: 2.2844 - accuracy: 0.1278 - val_loss: 2.3327 - val_accuracy: 0.0800
Epoch 63/100
900/900 [==============================] - 0s 96us/step - loss: 2.2842 - accuracy: 0.1322 - val_loss: 2.3327 - val_ac

In [46]:
model.evaluate(x_test, y_test)

1000/1000 [==============================] - 0s 17us/step


[2.312080795288086, 0.0989999994635582]

In [47]:
model.metrics_names

['loss', 'accuracy']

In [48]:
model.save('./dummy_model')

In [ ]:
## initialize the model
from keras.models import Sequential
from keras.layers import Input, Dense
model = Sequential()

In [ ]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.01,momentum=0.9, nesterov=True))

In [ ]:
## prepare a placeholder for input
# this is our input placeholder
inp = Input(shape=(784,)) # here shape (784, ) means we specify only the number of rows but we can input as many columns as we would like

In [ ]:
## Adding layers --> simple as .add()
## Dense means linear layer + activation
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=10, activation='softmax'))

In [ ]:
# Option I - gradient descent
model.compile(loss='mean_squared_error',
              optimizer='Adam',
              metrics=['mae', 'acc'])

# Option II - adadelta
# model.compile(optimizer='adadelta', loss='binary_crossentropy')

<a href="https://keras.io/optimizers/">more optimizers</a>

In [ ]:
# Training the model!
import numpy as np
X_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
X_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical( np.random.randint(10, size=(100, 1)), num_classes=10)


history = model.fit(X_train, y_train,
                    batch_size=128, epochs=20,
                    validation_data=(X_test, y_test))

In [ ]:
# Results of the model over epochs
history.history['val_loss']

In [ ]:
history.history['loss']

In [ ]:
model.summary()

In [ ]:
## Evaluate
loss_and_metrics = model.evaluate(X_test, y_test)

In [ ]:
loss_and_metrics

In [ ]:
### Useful
model.save('./model.h5') # Save your weights and computational graph
from keras.models import load_model
load_model('./model.h5') # loading the saved model from above

In [ ]:
!ls -lah

In [ ]:
from keras.applications.vgg16 import VGG16

In [ ]:
model = VGG16(weights='imagenet', include_top=False)
# model.save('./vgg16.h5')

In [ ]:
model.summary()

In [ ]:
ls -lath

### Your exercise:  Image reconstruction using auto-encoder

##### Import dataset - Mnist (handwritten digits)

In [ ]:
import os

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# keras imports for the dataset and building our neural network
from keras.datasets import mnist
from keras.models import Sequential, load_model, Input
from keras.layers.core import Dense, Dropout, Activation
from keras.layers import Conv2D, BatchNormalization
from keras.utils import np_utils

In [ ]:
### a. Load the Mnist dataset and split to train/test (use mnist.load_data())
### b. Plot few images with their label
### c. reshape images to 784 dim vector and normalize (divide by 255)
### d. Create a new model with 1 Dense layers sized 32 (encoder) with relu layer. 
### Then add a dense layer sized 784 with sigmoid activation.
### Run it for 50 epochs with batches of 256. Use binary cross-entropy. 
### e. Plot the model loss
### f. Use predict to encode and decode x_test

In [ ]:
# keras imports for the dataset and building our neural network
import keras
import os
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import (
    Dense,
    Dropout,
    Flatten,
    Conv2D,
    MaxPooling2D
)
from keras import backend as K

os.environ['TF_CPP_MIN_LOG_LEVEL']='3'
## This is to avoid getting hundreds of log messages

In [ ]:
from keras.models import Model

In [ ]:
batch_size = 256
num_classes = 10
epochs = 5

In [ ]:
# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [ ]:
x_train[0]

In [ ]:
if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [ ]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer='Adam',
              metrics=['accuracy'])

In [ ]:
model.summary()

In [ ]:
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])